# -*- coding: utf-8 -*-
"""QuizNajihah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3G6HzYcC3MdrwsLt6gNM_sQOZMFCes9
"""

# You can modify this file if you want
import pandas as pd
import matplotlib.pyplot as plt

# Define the add_revenue function locally
def add_revenue(df):
    """Adds 'revenue' column: units * price."""
    df['revenue'] = df['units'] * df['price']
    return df

# Load data
df = pd.read_csv('sales.csv')

# Add revenue column using the provided function
df = add_revenue(df)

# Save updated CSV
df.to_csv('sales_with_revenue.csv', index=False)

# Create and save a simple bar plot
plt.figure(figsize=(8, 5))
plt.bar(df['product'], df['revenue'])
plt.title('Revenue by Product')
plt.ylabel('Revenue ($)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('revenue_plot.png')

print("✅ Done! Check for sales_with_revenue.csv and revenue_plot.png")